name: PR Services Checks

on:
  pull_request:
    branches:
      -  main

jobs:
  pr-changes:
    name: Get PR changes
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'services/api/**/*.(go|mod|sum)'
              - 'services/api/.golangci.json'

  run-api-checks:
    name: Run API PR checks
    needs: pr-changes
    if: ${{ needs.pr-changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Lint API
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          working-directory: services/api
